# Generated by Django 5.1.1 on 2024-10-01 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("editor", "editor"),
                ],
                default="viewer",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default="This is a paragraph.")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
