# Generated by Django 5.1.1 on 2024-10-04 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_customuser_role_customuser_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
