# Generated by Django 5.1.1 on 2024-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_customuser_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("editor", "Editor"),
                ],
                max_length=10,
            ),
        ),
    ]
